from __future__ import annotations
import argparse, re, zipfile
from pathlib import Path, PurePosixPath

# Generic private-machine/topology signatures only. Never embed actual user hostnames,
# tailnet names, device names, account names, or IP addresses in this public scanner.
PRIVATE_LITERALS = (
    r"\local_share",
    r"\ollama\models",
)
PRIVATE_PATTERNS = (
    re.compile(r"\b[A-Za-z0-9-]+\.ts\.net\b", re.I),
    re.compile(r"\b100\.(?:6[4-9]|[78]\d|9\d|1[01]\d|12[0-7])(?:\.\d{1,3}){2}\b(?!/)"),
    re.compile(r"\b[A-Z]:\\Users\\(?!(?:NORM-HOST|USERNAME|USER)\\)[^\\\s]+\\", re.I),
)
TOKEN_PATTERNS = (
    re.compile(r"\bghp_[A-Za-z0-9]{20,}"),
    re.compile(r"\bgithub_pat_[A-Za-z0-9_]{20,}"),
    re.compile(r"\btskey-[A-Za-z0-9_-]{10,}"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\bsk-[A-Za-z0-9]{24,}\b"),
    re.compile(r"-----BEGIN (?:OPENSSH |RSA |EC )?PRIVATE KEY-----"),
)
TEXT_EXTS = {".py",".md",".txt",".json",".ini",".cmd",".bat",".ps1",".toml",".yaml",".yml",".cfg",".rst",".sha256",".gitignore"}
BLOCKED_PARTS = {".ssh","secrets","state","logs","workspace","temp","__pycache__"}
SELF = "tools/public_release_guard.py"

def scan_text(text: str, label: str) -> None:
    low=text.lower()
    for literal in PRIVATE_LITERALS:
        if literal in low:
            raise RuntimeError(f"{label}: private-machine path signature {literal!r}")
    for pattern in PRIVATE_PATTERNS:
        if pattern.search(text):
            raise RuntimeError(f"{label}: private-machine/topology pattern {pattern.pattern}")
    for pattern in TOKEN_PATTERNS:
        if pattern.search(text):
            raise RuntimeError(f"{label}: credential/private-key pattern {pattern.pattern}")

def scan_tree(root: Path) -> int:
    root=root.resolve(); checked=0
    for path in sorted(root.rglob("*")):
        if not path.is_file(): continue
        rel=path.relative_to(root).as_posix()
        parts=set(PurePosixPath(rel).parts)
        if ".git" in parts:
            continue
        if parts & BLOCKED_PARTS: raise RuntimeError(f"{rel}: blocked private/generated directory")
        if path.suffix.lower()==".pyc": raise RuntimeError(f"{rel}: generated bytecode")
        if rel=="src/Norm/core/norm.exe": raise RuntimeError(f"{rel}: generated norm.exe")
        if rel.startswith("src/Norm/tools/weasyprint/runtime/"): raise RuntimeError(f"{rel}: downloaded native runtime")
        if rel==SELF: checked+=1; continue
        if path.suffix.lower() in TEXT_EXTS or path.name==".gitignore":
            scan_text(path.read_text(encoding="utf-8",errors="ignore"),rel)
        checked+=1
    return checked

def scan_source_zip(path: Path) -> int:
    checked=0
    with zipfile.ZipFile(path) as zf:
        for info in zf.infolist():
            if info.is_dir(): continue
            rel=PurePosixPath(info.filename)
            parts=set(rel.parts)
            if parts & BLOCKED_PARTS: raise RuntimeError(f"{info.filename}: blocked private/generated directory")
            if info.filename.endswith(".pyc") or "__pycache__" in parts: raise RuntimeError(f"{info.filename}: generated cache")
            if info.filename.endswith("/core/norm.exe"): raise RuntimeError(f"{info.filename}: generated norm.exe")
            if "/tools/weasyprint/runtime/" in info.filename: raise RuntimeError(f"{info.filename}: downloaded native runtime")
            if rel.suffix.lower() in TEXT_EXTS:
                scan_text(zf.read(info).decode("utf-8",errors="ignore"),info.filename)
            checked+=1
    return checked

def main() -> int:
    ap=argparse.ArgumentParser()
    ap.add_argument("--tree",type=Path)
    ap.add_argument("--zip",dest="zip_path",type=Path)
    args=ap.parse_args()
    if bool(args.tree)==bool(args.zip_path):
        ap.error("choose exactly one of --tree or --zip")
    try:
        count=scan_tree(args.tree) if args.tree else scan_source_zip(args.zip_path)
        print(f"PUBLIC_RELEASE_GUARD_PASS files={count}")
        return 0
    except Exception as exc:
        print(f"PUBLIC_RELEASE_GUARD_FAIL {type(exc).__name__}: {exc}")
        return 2

if __name__=="__main__":
    raise SystemExit(main())
